config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations', 
                                    omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    root :to => "devise/sessions#new"
  end
  
  get 'pages/terms', to: 'pages#terms', as: 'terms'
  get 'pages/privacypolicy', to: 'pages#privacypolicy', as: 'privacypolicy'
  get 'posts/search', to: 'posts#search', as: 'search'

  resources :users, only: %i[show index] do
    member do
      get :following, :followers
    end
  end

  resource :user, only: %i[edit] do
    collection do
      patch 'update_password'
    end
  end

  resources :posts, only: %i[new create index show destroy] do
    resources :photos, only: %i[create]
    resources :likes, only: %i[create destroy]
    resources :comments, only: %i[create destroy]
    resources :bookmarks, only: %i[create destroy]
  end

  resources :relationships, only: %i[create destroy]
  resources :notifications, only: %i[index]
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy
  has_many :active_relationships, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :passive_relationships, class_name: 'Relationship', foreign_key: 'followed_id', dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :notifications, foreign_key: 'recipient_id'

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable, omniauth_providers: %i[facebook]
  validates :name, presence: true, length: { maximum: 50 }

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session['devise.facebook_data'] && session['devise.facebook_data']['extra']['raw_info']
        user.email = data['email'] if user.email.blank?
      end
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = User.create_unique_email
      user.password = Devise.friendly_token[0, 20]
      user.name = auth.info.name # assuming the user model has a name
    end
  end

  def self.create_unique_string
    SecureRandom.uuid
  end

  def self.create_unique_email
    User.create_unique_string + '@example.com'
  end

  def update_without_current_password(params, *options)
    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:current_password)
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end

  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    following.include?(other_user)
  end

  def feed
    following_ids = "SELECT followed_id FROM relationships
                     WHERE follower_id = :user_id"
    Post.where("user_id IN (#{following_ids})
                     OR user_id = :user_id", user_id: id)
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env['omniauth.auth'])
    p @user

    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication # this will throw if @user is not activated
      if is_navigational_format?
        set_flash_message(:notice, :success, kind: 'Facebook')
      end
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  protected

  def update_resource(resource, params)
    resource.update_without_current_password(params)
  end

  def after_update_path_for(resource)
    user_path(resource)
  end

  def after_sign_up_path_for(resource)
    user_path(resource)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find_by(id: params[:id])
    @posts = @user.posts.includes(:photos).order('created_at DESC')
  end

  def index
    @users = User.order('created_at DESC').page(params[:users_list]).per(5)
    @posts = Post.all.includes(:photos).order('created_at DESC').page(params[:posts_list]).per(9)
  end

  def edit
    @user = current_user
  end

  def update_password
    @user = current_user
    if @user.update_with_password(user_params)
      bypass_sign_in(@user)
      flash[:notice] = "パスワードが変更されました"
      redirect_to user_path(@user)
    else
      flash.now[:alert] = "変更に失敗しました"
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:current_password, :password, :password_confirmation)
  end
end

app/views/users/_follow.html.erb
<%= form_with model: current_user.active_relationships.build, local: true do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "フォローする", class: "btn btn-primary" %>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_with model: current_user.active_relationships.find_by(followed_id: @user.id), html: { method: :delete }, local: true do |f| %>
  <%= f.submit "フォロー中", class: "btn btn-success" %>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Password Change") %>

<div class="main">
  <div class="devise-outer">
    <div class="form-wrap">
      <%= form_with model:@user, url: update_password_user_path, method: :patch do |f| %>
        <div class="form-group">
          <%= f.label :current_password, "現在のパスワード" %>
          <%= f.password_field :current_password, autofocus: true, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :password, "新しいパスワード" %>
          <%= f.password_field :password, autofocus: true, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :password_confirmation, "新しいパスワードの確認" %>
          <%= f.password_field :password_confirmation, autofocus: true, class: "form-control" %>
        </div>
        <div class="form-group text-center">
          <%= f.submit "変更する", class: "btn btn-primary" %>
        </div>
      <% end %>
      <br>
      <%= link_to "Back", user_path(@user) %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, "Explore") %>

<div class="main">
  <div class="row mt-5">
    <div class="col-md-10 offset-md-2">
      <h4 class="text-center">フォローする人を見つけよう</h4>
      <div class="content-center mt-5">
        <%= paginate @users, :param_name => 'users_list' %>
      </div>
      <div class="card-group">
        <% @users.each do |user| %>
          <div class="card border border-0">
            <div class="card-img-top text-center mt-2">
              <%= image_tag avatar_url(user), class: "profile-icon" %>
            </div>
            <%= link_to user.username, user_path(user), class: "card-body text-center"%>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="row mt-5">
    <div class="col-md-10 offset-md-2">
      <h4 class="text-center">発見</h4>
      <div class="content-center mt-5">
        <%= paginate @posts, :param_name => 'posts_list' %>
      </div>
      <div class="row">
        <%= render "posts/photos_list", {posts: @posts}%>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, "Profile") %>
<div class="main mt-4">
  <div class="row">
    <div class="col-md-10 offset-md-2">
      <div class="row">
        <div class="col-md-2">
          <%= image_tag avatar_url(@user), class: "profile-icon-big" %>
        </div>
        <div class="col-md-10">
          <table style="height: 100px;">
            <tbody>
              <tr>
                <td class="profile-username"><%= @user.username %></td>
                <% if @user == current_user %>
                  <td>
                    <%= link_to "プロフィールを編集", edit_user_registration_path, class: "btn btn-outline-dark" %>
                  </td>
                  <td>
                    <div class="btn btn-outline-dark" data-toggle="modal" data-target="#exampleModal">
                      <i class="fas fa-cog"></i>
                    </div>
                    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                      <div class="modal-dialog" role="document">
                        <div class="modal-content">
                          <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">設定</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                              <span aria-hidden="true">×</span>
                            </button>
                          </div>
                          <div class="list-group">
                            <%= link_to "パスワードを変更", edit_user_path, class: "list-group-item list-group-item-action" %>
                            <%= link_to "サインアウト", destroy_user_session_path, method: :delete, class: "list-group-item list-group-item-action" %>
                            <%= link_to "キャンセル", "#", class: "list-group-item list-group-item-action", "data-dismiss": "modal" %>
                          </div>
                        </div>
                      </div>
                    </div>
                  </td>
                <% else %>
                  <td id="follow_form">
                    <% if current_user.following?(@user) %>
                      <%= render 'unfollow' %>
                    <% else %>
                      <%= render 'follow' %>
                    <% end %>
                  </td>
                <% end %>
              </tr>
            </tbody>
          </table>
          <div class="d-flex mt-2">
              <p class="ml-2">投稿 <span class="font-weight-bold"><%= @user.posts.count %></span>件</p>
              <p class="ml-2">フォロワー <span class="font-weight-bold"><%= @user.followers.count %></span>人</p>
              <p class="ml-2">フォロー中 <span class="font-weight-bold"><%= @user.following.count %></span>人</p>
          </div>
          <p class="font-weight-bold ml-2"><%= @user.self_intro %></p>
        </div>
      </div>
      </div>
    </div>
  </div>
  <div class="row mt-4">
    <div class="col-md-10 offset-md-2">
      <div class="row">
        <%= render "posts/photos_list", {posts: @posts}%>
      </div>
    </div>
  </div>
</div>