config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations', 
                                    omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    root :to => "devise/sessions#new"
  end
  
  get 'pages/terms', to: 'pages#terms', as: 'terms'
  get 'pages/privacypolicy', to: 'pages#privacypolicy', as: 'privacypolicy'
  get 'posts/search', to: 'posts#search', as: 'search'

  resources :users, only: %i[show index] do
    member do
      get :following, :followers
    end
  end

  resource :user, only: %i[edit] do
    collection do
      patch 'update_password'
    end
  end

  resources :posts, only: %i[new create index show destroy] do
    resources :photos, only: %i[create]
    resources :likes, only: %i[create destroy]
    resources :comments, only: %i[create destroy]
    resources :bookmarks, only: %i[create destroy]
  end

  resources :relationships, only: %i[create destroy]
  resources :notifications, only: %i[index]
end

app/views/partial/_footer.html.erb
<div class="main">
  <small>Copyright © Collabler</small>
</div>

app/views/partial/_navbar.html.erb
<nav class="navbar navbar-expand-sm navbar-light justify-content-center">
  <h2 class="brand-logo"><%= link_to "Collabler", posts_path %></h2>
  <ul class="navbar-nav">
    <li class="nav-item">
      <%= search_form_for @search, url: search_path do |f| %>
        <form class="form-inline" style="display: inline">
          <%= f.search_field :caption_cont, class: "mr-sm-2" %>
          <%= f.submit "検索", class: "btn btn-primary my-2 my-sm-0" %>
        </form>
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to new_post_path do %>
        <i class="fas fa-plus"></i>
        <span>投稿</span>
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to users_path do %>
        <i class="fab fa-wpexplorer"></i>
        <span>発見</span>
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to notifications_path do %>
        <i class="far fa-bell"></i>
        <span>通知</span>
      <% end %>
    </li>
    <li class="nav-item">
      <%= link_to user_path(current_user) do %>
        <i class="far fa-user-circle"></i>
        <span>プロフィール</span>
      <% end %>
    </li>
  </ul>
</nav>