config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations', 
                                    omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_scope :user do
    root :to => "devise/sessions#new"
  end
  
  get 'pages/terms', to: 'pages#terms', as: 'terms'
  get 'pages/privacypolicy', to: 'pages#privacypolicy', as: 'privacypolicy'
  get 'posts/search', to: 'posts#search', as: 'search'

  resources :users, only: %i[show index] do
    member do
      get :following, :followers
    end
  end

  resource :user, only: %i[edit] do
    collection do
      patch 'update_password'
    end
  end

  resources :posts, only: %i[new create index show destroy] do
    resources :photos, only: %i[create]
    resources :likes, only: %i[create destroy]
    resources :comments, only: %i[create destroy]
    resources :bookmarks, only: %i[create destroy]
  end

  resources :relationships, only: %i[create destroy]
  resources :notifications, only: %i[index]
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :user
  has_many :photos, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :bookmarks, -> { order(created_at: :desc) }, dependent: :destroy
  has_many :comments, dependent: :destroy

  accepts_nested_attributes_for :photos

  def already_liked?(user)
    Like.find_by(user_id: user.id, post_id: id)
  end

  def already_bookmarked?(user)
    Bookmark.find_by(user_id: user.id, post_id: id)
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: %i[show destroy]

  def new
    @post = Post.new
    @post.photos.build
  end

  def create
    @post = Post.new(post_params)
    if @post.photos.present?
      @post.save
      redirect_to post_path(@post)
      flash[:notice] = '投稿が保存されました'
    else
      redirect_to root_path
      flash[:alert] = '投稿が失敗しました'
    end
  end

  def index
    @posts = current_user.feed.includes(:photos).order('created_at DESC')
  end

  def show
  end

  def destroy
    if @post.user == current_user
      flash[:notice] = '投稿が削除されました' if @post.destroy
    else
      flash[:alert] = '投稿の削除に失敗しました'
    end
    redirect_to posts_path
  end

  def search
    @posts = @search_posts.page(params[:page]).per(9)
  end

  private

  def post_params
    params.require(:post).permit(:caption, photos_attributes: [:image]).merge(user_id: current_user.id)
  end

  def set_post
    @post = Post.find_by(id: params[:id])
  end
end

app/views/posts/_comment_list.html.erb
<% post.comments.each do |comment| %>
  <div class="mb-1">
    <% if comment.user == current_user %>
      <%= link_to "", post_comment_path(post.id, comment), method: :delete, remote: true, class: "delete-comment" %>
    <% end %>
    <%= link_to comment.user.name, user_path(comment.user), class: "text-dark font-weight-bold" %>
    <%= comment.comment %>
  </div>
<% end %>

app/views/posts/_comments_list.html.erb
<% post.comments.each do |comment| %>
  <div class="mb-1">
    <% if comment.user == current_user %>
      <%= link_to post_comment_path(post.id, comment), method: :delete, remote: true, class: "delete-comment" do %>
        <i class="far fa-times-circle"></i>
      <% end %>
    <% end %>
    <%= link_to comment.user.username, user_path(comment.user), remote: true, class: "text-dark font-weight-bold" %>
    <%= comment.comment %>
  </div>
<% end %>

app/views/posts/_like_text.html.erb
<strong>
  <% likes.each.with_index do |like, index| %>
    <% if likes.size == 1 %>
      <%= like.user.username %> </strong> が「いいね！」しました
    <% elsif like == likes.last %>
      </strong>and<strong>
      <%= + like.user.username %></strong> が「いいね！」しました
    <% elsif index > 1 %>
      </strong><%= "and " + (likes.size-index).to_s + " 他 " %> が「いいね！」しました
      <% break %>
    <% elsif index == likes.size-2 || index == 1 %>
      <%= like.user.username %>
    <% else %>
      <%= like.user.username + ", " %>
    <% end %>
  <% end %>
</strong>

app/views/posts/_photo_detail.html.erb
<div class="col-md-12">
  <div class="row">
    <div class="col-md-6">
      <%= image_tag post.photos.first.image.url(:medium), class: "img-thumbnail" %>
    </div>
    <div class="col-md-6">
      <div class="show-right">
        <div class="mt-2">
          <%= image_tag avatar_url(post.user), class: "profile-icon" %>
          <%= link_to user_path(post.user), class: "no-text-decoration" do %>
            <span class="card-username ml-2"><%= post.user.username %></span>
          <% end %>
        </div>
        <div class="d-flex mt-2">
          <div id="like-icon-post-<%= post.id.to_s %>" >
            <% if post.already_liked?(current_user).present? %>
              <%= link_to "Unlike", post_like_path(post.id, post.already_liked?(current_user)), method: :DELETE, remote: true %>
            <% else %>
              <%= link_to "Like", post_likes_path(post), method: :POST, remote: true %>
            <% end %>
          </div>
          <div id="bookmark-icon-post-<%= post.id.to_s %>", class="ml-2" >
            <% if post.already_bookmarked?(current_user).present? %>
              <%= link_to "Unbookmark", post_bookmark_path(post.id, post.already_bookmarked?(current_user)), method: :DELETE, remote: true %>
            <% else %>
              <%= link_to "Bookmark", post_bookmarks_path(post), method: :POST, remote: true %>
            <% end %>
          </div>
        </div>
        <div id="like-text-post-<%= post.id.to_s %>" class="mt-2">
          <%= render "posts/like_text", { likes: post.likes } %>
        </div>
        <div class="mt-1">
          <span><strong><%= post.user.name %></strong></span>
          <span><%= post.caption %></span>
        </div>    
        <div id="comment-post-<%= post.id.to_s %>", class="mt-1">
          <%= render 'posts/comments_list', { post: post } %>
          <%= link_to time_ago_in_words(post.created_at).upcase + "前", post_path(post),class: "post-time" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/_photos_list.html.erb
<% posts.each do |post| %>
  <div class="col-4 mt-4">
    <div data-toggle="modal" data-target="#exampleModal-<%= post.id.to_s %>">
      <%= image_tag post.photos.first.image.url(:medium), class: "card-img-top" %>
      <div class="modal fade show" id="exampleModal-<%= post.id.to_s %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" >
        <div class="modal-dialog modal-lg" role="document">
          <div class="modal-content">
            <div class="modal-body" style="display: block;">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
              <%= render 'posts/photo_detail', {post: post} %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/index.html.erb
<% provide(:title, "Home") %>

<% @posts.each do |post| %>
  <div class="main">
    <div class="col-md-6 offset-md-3">
      <div class="row">
        <div class="card mt-2">
          <div class="card-header">
            <%= link_to user_path(post.user) do %>
              <%= image_tag avatar_url(post.user), class: "profile-icon" %>
            <% end %>
            <%= link_to user_path(post.user), title: post.user.name do %>
              <span class="ml-2 card-username"><%= post.user.username %></span>
            <% end %>
            <% if post.user_id == current_user.id %>
              <%= link_to post_path(post), method: :delete do %>
                <span class="float-right bin"><i class="fas fa-trash"></i></span>
              <% end %>
            <% end %>
          </div>
          <%= link_to post_path(post) do %>
            <%= image_tag post.photos.first.image.url(:medium), class: "card-img-top" %>
          <% end %>
          <div class="card-body">
            <div class="d-flex">
              <div id="like-icon-post-<%= post.id.to_s %>", class="" >
                <% if post.already_liked?(current_user).present? %>
                  <%= link_to "Unlike", post_like_path(post.id, post.already_liked?(current_user)), method: :DELETE, remote: true %>
                <% else %>
                  <%= link_to "Like", post_likes_path(post), method: :POST, remote: true %>
                <% end %>
              </div>
              <div id="bookmark-icon-post-<%= post.id.to_s %>", class="ml-2" >
                <% if post.already_bookmarked?(current_user).present? %>
                  <%= link_to "Unbookmark", post_bookmark_path(post.id, post.already_bookmarked?(current_user)), method: :DELETE, remote: true %>
                <% else %>
                  <%= link_to "Bookmark", post_bookmarks_path(post), method: :POST, remote: true %>
                <% end %>
              </div>
            </div>
            <div id="like-text-post-<%= post.id.to_s %>" class="mt-2">
              <%= render "posts/like_text", { likes: post.likes } %>
            </div>
            <div class="mt-1">
              <span><strong><%= post.user.name %></strong></span>
              <span><%= post.caption %></span>
            </div>    
            <div id="comment-post-<%= post.id.to_s %>", class="mt-2">
              <%= render 'posts/comments_list', { post: post } %>
              <%= link_to time_ago_in_words(post.created_at).upcase + "前", post_path(post),class: "post-time" %>
            </div>
            <hr>
            <div id="comment-form-post-<%= post.id.to_s %>">
              <%= form_with model: [post, Comment.new], remote: true do |f| %>
                <%= f.hidden_field :user_id, value: current_user.id %>
                <%= f.hidden_field :post_id, value: post.id %>
                <%= f.text_field :comment, class: "form-control", placeholder: "コメント ...", autocomplete: :off %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/posts/new.html.erb
<% provide(:title, "New Post") %>

<div class="main">
  <div class="row mt-5">
    <div class="col-md-10 offset-md-2">
      <div class="card card-post-new mt-2">
        <div class="card-header">
          <h4 class="text-center">投稿作成</h4>
        </div>
        <div class="card-body">
          <%= form_with model: @post do |f| %>
            <div class="form-group mt-2">
                <%= f.fields_for :photos do |i| %>
                  <%= i.file_field :image, accept: 'image/jpg,image/jpeg,image/png', class: "btn"%>
                <%= f.text_field :caption, class: "form-control ml-2 mt-2", placeholder: "キャプションを書く" %>
                <% end %>
            </div>
            <div class="card-footer text-center">
              <%= f.submit "投稿する", class: "btn btn-primary" %>
            </div>
          <% end %>
          <%= link_to "Back", posts_path %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/search.html.erb
<% provide(:title, "Search Result") %>

<div class="main">
  <div class="row mt-5">
    <div class="col-md-10 offset-md-2">
      <h4 class="text-center">検索結果</h4>
      <div class="content-center mt-5">
        <%= paginate @posts %>
      </div>
      <div class="row">
        <%= render "posts/photos_list", {posts: @posts}%>
      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<% provide(:title, "Post Detail") %>

<div class="main">
  <div class="col-md-10 offset-md-2  my-5">
    <div class="row">
      <div class="col-md-6">
        <%= image_tag @post.photos.first.image.url(:medium), class: "img-thumbnail" %>
      </div>
      <div class="col-md-6">
        <div class="show-right">
          <div class="mt-2">
            <%= image_tag avatar_url(@post.user), class: "profile-icon" %>
            <%= link_to user_path(@post.user), class: "no-text-decoration" do %>
              <span class="card-username ml-2"><%= @post.user.name %></span>
            <% end %>
            <% if @post.user_id == current_user.id %>
              <%= link_to post_path(@post), method: :delete do %>
                <span class="float-right bin"><i class="fas fa-trash"></i></span>
              <% end %>
            <% end %>
          </div>
          <div class="mt-2">
            <strong><%= @post.user.name %></strong>
            <%= @post.caption %>
          </div>
          <div id="comment-post-<%= @post.id.to_s %>", class="mt-2">
            <%= render 'comments_list', post: @post %>
          </div>
          <div class="d-flex mt-4">
            <div id="like-icon-post-<%= @post.id.to_s %>">
              <% if @post.already_liked?(current_user).present? %>
                <%= link_to "Unlike", post_like_path(@post.id, @post.already_liked?(current_user)), method: :DELETE, remote: true %>
              <% else %>
                <%= link_to "Like", post_likes_path(@post), method: :POST, remote: true %>
              <% end %>
            </div>
            <div id="bookmark-icon-post-<%= @post.id.to_s %>", class="ml-2" >
              <% if @post.already_bookmarked?(current_user).present? %>
                <%= link_to "Unbookmark", post_bookmark_path(@post.id, post.already_bookmarked?(current_user)), method: :DELETE, remote: true %>
              <% else %>
                <%= link_to "Bookmark", post_bookmarks_path(@post), method: :POST, remote: true %>
              <% end %>
            </div>
          </div>
          <div id="like-text-post-<%= @post.id.to_s %>" class="mt-2">
            <%= render "like_text", { likes: @post.likes } %>
          </div>
          <div id="comment-form-post-<%= @post.id.to_s %>" class="mt-4">
            <%= form_with model: [@post, Comment.new], remote: true do |f| %>
              <%= f.hidden_field :user_id, value: current_user.id %>
              <%= f.hidden_field :post_id, value: @post.id %>
              <%= f.text_field :comment, class: "form-control", placeholder: "コメント ...", autocomplete: :off %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>